name: Build macOS App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install create-dmg
      run: brew install create-dmg
      
    - name: Build
      run: |
        xcodebuild -project PCTimelapse.xcodeproj \
          -scheme PCTimelapse \
          -configuration Release \
          -archivePath build/PCTimelapse.xcarchive \
          archive
        
        # Export archive to app
        xcodebuild -archivePath build/PCTimelapse.xcarchive \
          -exportArchive \
          -exportPath build/export \
          -exportOptionsPlist exportOptions.plist
    
    - name: Create DMG
      run: |
        # Create exportOptions.plist
        cat > exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>developer-id</string>
            <key>teamID</key>
            <string>${{ secrets.TEAM_ID }}</string>
        </dict>
        </plist>
        EOF
        
        APP_PATH="build/export/PCTimelapse.app"
        DMG_PATH="build/PCTimelapse.dmg"
        
        # 创建临时目录用于DMG
        mkdir -p build/dmg
        cp -r "$APP_PATH" build/dmg/
        
        # 创建 DMG
        create-dmg \
          --volname "PCTimelapse" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "PCTimelapse.app" 200 190 \
          --hide-extension "PCTimelapse.app" \
          --app-drop-link 600 185 \
          "$DMG_PATH" \
          "build/dmg/"
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v3
      with:
        name: PCTimelapse
        path: build/PCTimelapse.dmg
    
    # 如果是发布标签，则创建 Release
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/PCTimelapse.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
